name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 1.8
        uses: actions/setup-java@main
        with:
          java-version: 1.8
      - uses: actions/cache@main
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean shadowJar
      - uses: actions/upload-artifact@main
        with:
          name: WorldGuard
          path: worldguard-bukkit/build/libs